name: Deploy to VPS

on:
  push:
    branches:
      - release

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}
          
      - name: Add VPS to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.VPS_IP }} >> ~/.ssh/known_hosts
      
      - name: Deploy to server
        run: |
          ssh deployer@${{ secrets.VPS_IP }} <<'EOF'
            mkdir -p /home/deployer/successscienceacademy.com
            cd /home/deployer/successscienceacademy.com
            git fetch origin release
            git reset --hard origin/release
            docker-compose pull
            docker-compose up -d --build
          EOF

      - name: Build and start Docker container
        run: |
          ssh deployer@<your-vps-ip> <<'EOF'
            cd /home/deployer/successscienceacademy.com
            docker compose down
            docker compose up -d --build
          EOF
