name: Deploy to VPS on release branch

on:
  push:
    branches:
      - release

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH agent
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}
    
      - name: Add VPS to known_hosts
        run: |
          ssh-keyscan -H ${{ secrets.VPS_IP }} >> ~/.ssh/known_hosts

      - name: SSH into VPS and restart containers
        run: |
          ssh deployer@${{ secrets.VPS_IP }} << 'EOF'
            cd /home/deployer/ssa-website/
            docker-compose pull
            docker-compose up -d --build
          EOF
